publication_index:
    path:     /publications
    defaults: { _controller: "AppBundle:Publication:index" }
    methods:  GET

publication_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Publication:show" }
    methods:  GET

publication_new:
    path:     /publier
    defaults: { _controller: "AppBundle:Publication:new" }
    methods:  [GET, POST]

publication_edit:
    path:     /admin/publication/{id}/edit
    defaults: { _controller: "AppBundle:Publication:edit" }
    methods:  [GET, POST]

publication_delete:
    path:     /admin/publication/{id}/delete
    defaults: { _controller: "AppBundle:Publication:delete" }
    methods:  DELETE