science_index:
    path:     /admin/sciences
    defaults: { _controller: "AppBundle:Science:index" }
    methods:  GET

science_show:
    path:     /admin/sciences/{id}
    defaults: { _controller: "AppBundle:Science:show" }
    methods:  GET

science_new:
    path:     /admin/sciences/new
    defaults: { _controller: "AppBundle:Science:new" }
    methods:  [GET, POST]

science_edit:
    path:     /admin/sciences/{id}/edit
    defaults: { _controller: "AppBundle:Science:edit" }
    methods:  [GET, POST]

science_delete:
    path:     /admin/sciences/{id}/delete
    defaults: { _controller: "AppBundle:Science:delete" }
    methods:  DELETE