app_science:
    resource: "@AppBundle/Resources/config/routing/science.yml"
    prefix:   /

app_publication:
        resource: "@AppBundle/Resources/config/routing/publication.yml"
        prefix:   /

app_admin:
    resource: "routing/admin.yml"
    prefix:   /admin

app_public:
    resource: "routing/public.yml"
